#!/usr/bin/env python3
"""Bundle JSON data files into a single data.js global so the site works from file://."""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

bundle = {
    "predictions":  json.loads((DATA / "predictions.json").read_text()),
    "track_record": json.loads((DATA / "track_record.json").read_text()),
    "metadata":     json.loads((DATA / "metadata.json").read_text()),
}

js = "/* Auto-generated by scripts/build_data_js.py — do not edit by hand. */\n"
js += "window.UKE_DATA = " + json.dumps(bundle, indent=2, ensure_ascii=False) + ";\n"

(DATA / "data.js").write_text(js, encoding="utf-8")
print(f"Wrote {DATA / 'data.js'} ({len(js):,} bytes)")
